/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.modules.FoodOrder;
import model.services.FoodOrderServices;
import model.services.OtherOrderServices;

/**
 *
 * @author viliu
 */
public class CheckoutPage extends javax.swing.JFrame {
         List<FoodOrder> orders = new ArrayList<>();
         Map<String, Object> userInfo = new HashMap();
         int restaurantID;
         String restaurantName;
         double totalCost = 0;
         boolean isDelivery = false;
         String address;
         String number;
         
    /**
     * Creates new form CheckoutPage
     */
    public CheckoutPage() {
        initComponents();
        Color col = new Color(204,204,204);
        getContentPane().setBackground(col);
        
    }
    
     public CheckoutPage(Map<String, Object> userInfo, int restaurantID, List<FoodOrder> orders, String restaurantName) {
        initComponents();
        this.orders = orders;
        this.userInfo = userInfo;
        this.restaurantID = restaurantID;
        this.restaurantName = restaurantName;
        fillTable();
        sumNumberLabel.setText(Double.toString(totalCost));
        restaurantNameLabel.setText(restaurantName);
        setLocationRelativeTo(null);
        this.setTitle("Checkout Page");
    }
     
     
     
     public CheckoutPage(Map<String, Object> userInfo, int restaurantID, List<FoodOrder> orders, String restaurantName, String address, String number) {
        initComponents();
        this.orders = orders;
        this.userInfo = userInfo;
        this.restaurantID = restaurantID;
        this.restaurantName = restaurantName;
        this.isDelivery = true;
        this.address = address;
        this.number = number;
        fillTable();
        sumNumberLabel.setText(Double.toString(totalCost));
        restaurantNameLabel.setText(restaurantName);
        this.setTitle("Checkout Page");
        
    }
     
     
     
     public void fillTable(){
         
         String columns[] = {"Pavadinimas", "Kiekis", "Kaina"};
         
         
        String data[][];
        if(isDelivery)
            data = new String[orders.size() + 1][3];
        else
            data = new String[orders.size()][3];
         
       
         for(int i=0; i<orders.size(); i++) {
             data[i][0] = orders.get(i).foodname();
             data[i][1] = Integer.toString(orders.get(i).amount());
             data[i][2] = Double.toString(orders.get(i).cost());
             
             totalCost = totalCost + orders.get(i).cost();
         }
         
         if(isDelivery)
         {
             data[orders.size()][0] = "Maisto pristatymas į namus";
             data[orders.size()][1] = " ";
             data[orders.size()][2] = Double.toString(2);
             totalCost += 2;
         }
         
         DefaultTableModel model = new DefaultTableModel(data, columns);
         jTable1.setModel(model);
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sumLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        Buy = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        sumNumberLabel = new javax.swing.JLabel();
        restourantLabel = new javax.swing.JLabel();
        restaurantNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Maistas", "Kiekis", "Kainas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(220);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        sumLabel.setText("Suma:");

        backButton.setText("Atgal");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Atšaukti");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        Buy.setText("Pirkti");
        Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Užsakymas");

        restourantLabel.setText("Restoranas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(restourantLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(restaurantNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(backButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sumNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addGap(210, 210, 210)
                                .addComponent(Buy))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restourantLabel)
                    .addComponent(restaurantNameLabel))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumLabel)
                    .addComponent(backButton)
                    .addComponent(sumNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(Buy))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new MenuPage(userInfo, restaurantID, restaurantName).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        new OrderPage(userInfo).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyActionPerformed
        

    try {
        if(isDelivery)
        {
            int newID = OtherOrderServices.newDeliveryToHome(address, 2, LocalTime.now(), LocalDate.now(), number);
            FoodOrderServices.newOrder_Food(orders, LocalDate.now(), LocalTime.now(), "Vykdoma", newID, 0, false, (int)userInfo.get("ID"), true);
        }
        else
            FoodOrderServices.newOrder_Food(orders, LocalDate.now(), LocalTime.now(), "Vykdoma", 0, 0, false, (int)userInfo.get("ID"), false);
        JOptionPane.showMessageDialog(null, "Užsakymas įvykdytas!");
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Užsakymas neįvykdytas!");
        Logger.getLogger(CheckoutPage.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    new MainPage(userInfo).setVisible(true);
    this.setVisible(false);
    
    }//GEN-LAST:event_BuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckoutPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buy;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel restaurantNameLabel;
    private javax.swing.JLabel restourantLabel;
    private javax.swing.JLabel sumLabel;
    private javax.swing.JLabel sumNumberLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
