package presentation;


import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;

import model.modules.Restaurant;
import model.services.FoodOrderServices;

/**
 *
 * @author maxim
 */
public class RestaurantsPage extends javax.swing.JFrame {
    List<Restaurant> restaurantList = new ArrayList<>();
    Map<String, Object> userInfo = new HashMap();
    
    /**
     * Creates new form RestaurantsPage
     */
    public RestaurantsPage(Map<String, Object> userInfo) throws SQLException{
        generateRestaurantsList();
        this.userInfo = userInfo;
        setLocationRelativeTo(null);
        this.setTitle("Restaurants Page");
    }
    
    
  
    
    
    private void generateRestaurantsList() throws SQLException{
        List<Restaurant> restaurantList = FoodOrderServices.getRestaurantList();
      
        setLayout(new BorderLayout()); // Set layout for the JFrame

        // Create a JPanel with a vertical BoxLayout to contain each item and its button
        JPanel itemsPanel = new JPanel();
        itemsPanel.setLayout(new BoxLayout(itemsPanel, BoxLayout.Y_AXIS));

        // Scroll Pane in case of many items
        JScrollPane scrollPane = new JScrollPane(itemsPanel);
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        // Panel to hold the scroll pane
        JPanel containerPanel = new JPanel(new BorderLayout());
        containerPanel.add(scrollPane, BorderLayout.CENTER);
        containerPanel.setPreferredSize(new Dimension(375, 300)); // Set preferred size

        for (Restaurant restaurant : restaurantList) {
            addItem(restaurant.ID(), restaurant.address(), itemsPanel);
        }

        // Additional components
        JLabel header = new JLabel("Restoranu sarasas.", SwingConstants.CENTER);
        JButton returnButton = new JButton("Atgal");
        returnButton.setName("backButton");
        returnButton.addActionListener(e -> {
            
            try {
                returnPress();
            } catch (SQLException ex) {
                Logger.getLogger(RestaurantsPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            
               
            
        });
        
        
        
        
        //--------
        JPanel bottomPanel = new JPanel(new BorderLayout());

        bottomPanel.add(returnButton, BorderLayout.WEST);
        
        add(header, BorderLayout.NORTH);
        add(containerPanel, BorderLayout.CENTER);
        add(bottomPanel, BorderLayout.SOUTH);

        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
        
        
    }
    
    
    private void addItem(int id, String address, JPanel itemsPanel) {
    JPanel itemPanel = new JPanel(new BorderLayout());

    JLabel idLabel = new JLabel(Integer.toString( id));
    //idLabel.setVisible(false);

    JLabel itemLabel = new JLabel(address);
    itemLabel.setVerticalAlignment(SwingConstants.TOP);
    itemPanel.add(itemLabel, BorderLayout.WEST);

    // Create a new panel for the buttons
    JPanel buttonsPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
    JButton buyButton = new JButton("Meniu");
    buyButton.setName(address);
    buyButton.addActionListener(e -> {
        try {
            openMenu(id, address);
        } catch (SQLException ex) {
            Logger.getLogger(RestaurantsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    });

    buttonsPanel.add(buyButton);

    // Add the buttons panel to the right of the item panel
    itemPanel.add(buttonsPanel, BorderLayout.EAST);

    itemsPanel.add(itemPanel);
        
        
        
    }
    
    
    private void openMenu(int id, String name) throws SQLException{
        new MenuPage(userInfo, id, name).setVisible(true);
        this.setVisible(false);
    }
    
    private void returnPress() throws SQLException{
        new OrderPage(userInfo).setVisible(true);
        this.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
private javax.swing.JLabel costLabel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
